const ENV_TYPE = {
  dev: 'development',
  prod: 'production',
};

const DEFAULT_PORT = 5000;
const DEFAULT_ENV = ENV_TYPE.dev;

const DEFAULT_DB_CONNECTION_LIMIT = 10;
const DEFAULT_DB_QUERY_LIMIT = 0;

const MAX_BODY_LIMIT = '10kb';
const MAX_RATE_LIMIT = 100;
const MAX_LIMIT_TIME = 15 * 60 * 1000; // 15 minutes

const HTTP_METHODS = ['GET', 'POST', 'PUT', 'DELETE', 'PATCH'];
const HTTP_HEADERS = ['Content-Type', 'Authorization'];

const MORGAN_LOG_TYPE = {
  dev: 'dev',
  combined: 'combined',
};

const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  REQUEST_TIMEOUT: 408,
  CONFLICT: 409,
  LENGTH_REQUIRED: 411,
  PAYLOAD_TOO_LARGE: 413,
  URI_TOO_LONG: 414,
  UNSUPPORTED_MEDIA_TYPE: 415,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
} as const;

export {
  DEFAULT_DB_CONNECTION_LIMIT,
  DEFAULT_DB_QUERY_LIMIT,
  DEFAULT_ENV,
  DEFAULT_PORT,
  ENV_TYPE,
  HTTP_HEADERS,
  HTTP_METHODS,
  HTTP_STATUS,
  MAX_BODY_LIMIT,
  MAX_LIMIT_TIME,
  MAX_RATE_LIMIT,
  MORGAN_LOG_TYPE,
};
