name: Publish utils-date

on:
  push:
    branches: [main]
    paths:
      - 'libs/utils-date/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
          cache: 'pnpm'
          package-manager: pnpm@10.3.0
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build library
        run: pnpm nx build utils-date --prod
      - name: Publish package
        working-directory: dist/libs/utils-date
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
